// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* stick2;
	Joystick* stick1;
	JoystickButton* clawWheelToggleButton;
	JoystickButton* clawToggleButton;
	JoystickButton* onlyPullBack;
	JoystickButton* onlyShootButton;
	JoystickButton* shootButton;
	JoystickButton* angleDownButton;
	JoystickButton* angleUpButton;
	JoystickButton* shiftButton2;
	JoystickButton* shiftButton1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getStick1();
	Joystick* getStick2();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	float getDrvX();
	float getDrvY();
};
#endif
