// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Solenoid* RobotMap::drivetrainGear1 = NULL;
Solenoid* RobotMap::drivetrainGear2 = NULL;
SpeedController* RobotMap::drivetrainLeft = NULL;
SpeedController* RobotMap::drivetrainRight = NULL;
RobotDrive* RobotMap::drivetrainchassis = NULL;
Gyro* RobotMap::drivetrainGyro = NULL;
Encoder* RobotMap::drivetrainLeftEncoder = NULL;
Encoder* RobotMap::drivetrainRightEncoder = NULL;
SpeedController* RobotMap::trunnionArmMotor1 = NULL;
SpeedController* RobotMap::trunnionArmMotor2 = NULL;
AnalogChannel* RobotMap::trunnionArmAngle = NULL;
SpeedController* RobotMap::shooterWinch = NULL;
DigitalInput* RobotMap::shooterEye = NULL;
Solenoid* RobotMap::shooterFireSolenoid1 = NULL;
Solenoid* RobotMap::shooterFireSolenoid2 = NULL;
SpeedController* RobotMap::clawClawWheel = NULL;
Solenoid* RobotMap::clawClawSolenoid = NULL;
Relay* RobotMap::visionledSpike = NULL;
DigitalInput* RobotMap::lightsBallEye = NULL;
Relay* RobotMap::lightsClawLeds = NULL;
Relay* RobotMap::compressorSubsystemCompressorSpike = NULL;
DigitalInput* RobotMap::compressorSubsystemCompressorPressureSwitch = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	drivetrainGear1 = new Solenoid(1, 1);
	lw->AddActuator("Drivetrain", "Gear1", drivetrainGear1);
	
	drivetrainGear2 = new Solenoid(1, 2);
	lw->AddActuator("Drivetrain", "Gear2", drivetrainGear2);
	
	drivetrainLeft = new Talon(1, 1);
	lw->AddActuator("Drivetrain", "Left", (Talon*) drivetrainLeft);
	
	drivetrainRight = new Talon(1, 2);
	lw->AddActuator("Drivetrain", "Right", (Talon*) drivetrainRight);
	
	drivetrainchassis = new RobotDrive(drivetrainLeft, drivetrainRight);
	
	drivetrainchassis->SetSafetyEnabled(true);
        drivetrainchassis->SetExpiration(0.1);
        drivetrainchassis->SetSensitivity(0.5);
        drivetrainchassis->SetMaxOutput(1.0);
        
	drivetrainGyro = new Gyro(1, 1);
	lw->AddSensor("Drivetrain", "Gyro", drivetrainGyro);
	drivetrainGyro->SetSensitivity(0.007);
	drivetrainLeftEncoder = new Encoder(1, 3, 1, 4, false, Encoder::k4X);
	lw->AddSensor("Drivetrain", "LeftEncoder", drivetrainLeftEncoder);
	drivetrainLeftEncoder->SetDistancePerPulse(1.0);
        drivetrainLeftEncoder->SetPIDSourceParameter(Encoder::kRate);
        drivetrainLeftEncoder->Start();
	drivetrainRightEncoder = new Encoder(1, 1, 1, 2, false, Encoder::k4X);
	lw->AddSensor("Drivetrain", "RightEncoder", drivetrainRightEncoder);
	drivetrainRightEncoder->SetDistancePerPulse(1.0);
        drivetrainRightEncoder->SetPIDSourceParameter(Encoder::kRate);
        drivetrainRightEncoder->Start();
	trunnionArmMotor1 = new Talon(1, 3);
	lw->AddActuator("Trunnion", "ArmMotor1", (Talon*) trunnionArmMotor1);
	
	trunnionArmMotor2 = new Talon(1, 4);
	lw->AddActuator("Trunnion", "ArmMotor2", (Talon*) trunnionArmMotor2);
	
	trunnionArmAngle = new AnalogChannel(1, 2);
	lw->AddSensor("Trunnion", "ArmAngle", trunnionArmAngle);
	
	shooterWinch = new Talon(1, 6);
	lw->AddActuator("Shooter", "Winch", (Talon*) shooterWinch);
	
	shooterEye = new DigitalInput(1, 8);
	lw->AddSensor("Shooter", "Eye", shooterEye);
	
	shooterFireSolenoid1 = new Solenoid(1, 4);
	lw->AddActuator("Shooter", "FireSolenoid1", shooterFireSolenoid1);
	
	shooterFireSolenoid2 = new Solenoid(1, 3);
	lw->AddActuator("Shooter", "FireSolenoid2", shooterFireSolenoid2);
	
	clawClawWheel = new Talon(1, 5);
	lw->AddActuator("Claw", "ClawWheel", (Talon*) clawClawWheel);
	
	clawClawSolenoid = new Solenoid(1, 5);
	lw->AddActuator("Claw", "ClawSolenoid", clawClawSolenoid);
	
	visionledSpike = new Relay(1, 3);
	lw->AddActuator("Vision", "ledSpike", visionledSpike);
	
	lightsBallEye = new DigitalInput(1, 6);
	lw->AddSensor("Lights", "BallEye", lightsBallEye);
	
	lightsClawLeds = new Relay(1, 1);
	lw->AddActuator("Lights", "ClawLeds", lightsClawLeds);
	
	compressorSubsystemCompressorSpike = new Relay(1, 2);
	lw->AddActuator("CompressorSubsystem", "CompressorSpike", compressorSubsystemCompressorSpike);
	
	compressorSubsystemCompressorPressureSwitch = new DigitalInput(1, 7);
	lw->AddSensor("CompressorSubsystem", "CompressorPressureSwitch", compressorSubsystemCompressorPressureSwitch);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
