// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "AutonDrive.h"
#include <cmath>
AutonDrive::AutonDrive(float timer, float speed) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	time = timer;
	rate = speed;
}
// Called just before this Command runs the first time
void AutonDrive::Initialize() {
	//Robot::drivetrain->DistanceReset();
	SetTimeout(time);
}
// Called repeatedly when this Command is scheduled to run
void AutonDrive::Execute() {
	//if(fabs(Robot::drivetrain->GetDistance()) < distance) {
	Robot::drivetrain->Go(rate);
	//}
}
// Make this return true when this Command no longer needs to run execute()
bool AutonDrive::IsFinished() {
	/*if(fabs(Robot::drivetrain->GetDistance()) >= distance) {
	 return true;
	 }
	 else {
	 return false;
	 }*/
	return IsTimedOut();
}
// Called once after isFinished returns true
void AutonDrive::End() {
	Robot::drivetrain->Stop();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonDrive::Interrupted() {
}
