// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef TRUNNION_H
#define TRUNNION_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Trunnion: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* armMotor1;
	SpeedController* armMotor2;
	AnalogChannel* armAngle;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static const float GOALANGLE;
	static const float MIDZONEANGLE;
	static const float TRUSSANGLE;
	static const float FLOORANGLE;
	static const float MINANGLE;
	static const float MAXANGLE;
	static const float AUTON1ANGLE;
	static const float AUTON2ANGLE;
	static const float CROSSSHOT;
	Trunnion();
	void InitDefaultCommand();
	float GetAngle();
	void SetAngleMotors(float rate);
};
#endif
